### PR TITLE
Add Boile The Water Service

### PR DESCRIPTION
**Pull request by leranp**
The button doesn't work, so I add a service for this action

### CODE REVIEW

**Comment by taltaub22** [comment]
Hi!
Thanks for adding this service.

Can you please explain the usage of it? 
(There is already a button that enables boiling the water)

Also, please add the needed text to the readme file

**Comment by leranp** [comment]
> Hi!
> Thanks for adding this service.
> 
> Can you please explain the usage of it? 
> (There is already a button that enables boiling the water)
> 
> Also, please add the needed text to the readme file

Hi,
The button isn't working for me, i tried to fix the button code but without success, so i created a service for that.
Please let me know if the button isn't working only for me, and if not can you please fix it.

**Comment by taltaub22** [comment]
The button is working for me as expected.

Try and check the logs while you press the button

**Comment by leranp** [comment]
> The button is working for me as expected.
> 
> Try and check the logs while you press the button

There's no button, the component doesn't create them, please look at the issue that I opened to see the log error

**Comment by leranp** [comment]
> Hi! Thanks for adding this service.
> 
> Can you please explain the usage of it? (There is already a button that enables boiling the water)
> 
> Also, please add the needed text to the readme file

the service was added to readme file, please approve

**Comment by guy-suli** [comment]
The boil button is not functioning for me either, but all the data, including the sync, daily water consumption, weekly water consumption and etc, is working fine.

**Comment by leranp** [comment]
> The boil button is not functioning for me either, but all the data, including the sync, daily water consumption, weekly water consumption and etc, is working fine.

Copy the changes from my PR and the new service will be available

@taltaub22  please approve, it's not just me

**Review by taltaub22 — APPROVED** [review]
Approved

**Pull request merged**
